all: part1 part2_1and2 part2_3 part2_4 part3

part1: 
	gcc -o part1 part1.c

part2_1and2:
	gcc -o part2_1and2 part2_1and2.c

part2_3:
	gcc -o part2_3 part2_3.c

part2_4:
	gcc -o part2_4 part2_4.c

part3:
	gcc -o part3 part3.c

clean:
	rm part1 part2_1and2 part2_3 part2_4 part3
